### PR TITLE
Added flag to skip SSL verification

### PR DESCRIPTION
**Pull request by ndarr**
Added a command line option to disable the SSL verification when connecting to a Moodle Instance

### CODE REVIEW

**Comment by C0D3D3V** [comment]
Nice! Thank you very much :) I will merge it later. 

I actually used this when I tested the downloader on windows 7 in my virtual machine. 

I wonder what's going wrong. I'm sure I tested the downloader in the beginning and it worked without deactivating the ssl verification.

Do you have any idea why this is so? I haven't tried it under windows 10, does it work there? I have also tested it with Python 3.6, even there it only works without ssl verification.

weird

**Comment by ndarr** [comment]
I now executed it on my Win10 machine and it wasn't necessary to skip the verification. However on my linux machine I needed the flag.

**Comment by ndarr** [comment]
I experimented with the ssl library from python and my observations were that on my Win10 machine calling `ssl.create_default_context().get_ca_certs()` returns a list of CA certs as expected but on Linux it just returns an empty list.

**Comment by C0D3D3V** [comment]
This is really very strange, I have heard about this problem in many threads. Seems to be a bigger problem since Python 3.6. 
With my Arch Linux the problem does not occur.

**Pull request merged**
